**예시문제**

while문을 사용하여 다음과 같이 #을 표시하는 프로그램을 작성해 보자.

#
##
###
####
#####

In [ ]:
counter = 1
while counter <= 5:
  print ('#'*counter)
  counter += 1

**실습문제 1**

홍길동 씨의 과목별 점수는 국어 80점, 영어 75점, 수학 55점이다. 아래와 같이 점수를 나타낸 리스트를 이용해 평균을 구해서 출력하시오.

In [ ]:
scores=[80, 75, 55]

#Implement here
print(sum(scores) / 3)

**실습문제 2**

홍길동씨의 주민등록번호를 아래와 같이 변수로 선언하였다. 생년월일 부분과 뒤의 숫자부분을 나누어 두 줄로 출력해보자.

In [ ]:
pin = "881120-1068234"

#Implement here
print(pin[:6])
print(pin[7:])

**실습문제 3**

아래와 같은 딕셔너리가 있을 때, Key: ‘D’, Value: 100 의 쌍을 딕셔너리에 추가하고, 딕셔너리로부터 ‘D’에 해당하는 값을 추출하여 출력해보자

In [ ]:
a = {'A':90, 'B':80, 'C':70}

#Implement here
a['D'] = 100
print(a['D'])

**실습문제 4**

while문을 활용하여 1부터 1000까지의 자연수 중 3의 배수의 합을 구해서 출력하시오.

In [ ]:
#Implement here
a = 1
total = 0
while a <= 1000:
  if a % 3 == 0:
    total += a
  a += 1
print(total)

**실습문제 5**

사용자가 -1을 입력하기 전까지 입력하는 모든 수를 리스트에 저장했다가, -1을 입력하면 

1) 지금까지 입력된 수를 리스트로 출력

2) 합계 출력

3) 숫자 개수 출력

을 수행하는 프로그램을 구현하시오.
(사용자는 -1 및 자연수만 입력한다고 가정)

<실행 예시>

![image.png]()

In [ ]:
nums = []
while True:
  curr_num = int(input("0 이상의 숫자를 입력해주세요(-1은 종료): "))
  
  #Implement here
  if curr_num == -1:
    print("숫자 리스트: {}".format(nums))
    print("합계: {}".format(sum(nums)))
    print("개수: {}".format(len(nums)))
    break
  else:
    nums.append(curr_num)